# Generated by Django 5.2.10 on 2026-01-28 01:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedEligibilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_request_id', models.IntegerField(help_text='Primary key of the original EligibilityRequest.')),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('RESPONDED', 'Responded')], max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_eligibility_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedClientQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('eligibility', models.CharField(choices=[('UNKNOWN', 'Not reviewed yet'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not eligible')], default='UNKNOWN', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('archived_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='requestsapp.archivedeligibilityrequest')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('RESPONDED', 'Responded')], default='PENDING', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(help_text='Partner user who submitted the request.', on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('eligibility', models.CharField(choices=[('UNKNOWN', 'Not reviewed yet'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not eligible')], default='UNKNOWN', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='requestsapp.eligibilityrequest')),
            ],
        ),
    ]
